server:
  port: 8083
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: order_db
    password: sarasu10
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  circuitbreaker:
    instances:
      paymentServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 60
        slowCallDurationThreshold: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 15s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        ignoreExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException

  timelimiter:
    instances:
      paymentServiceCircuitBreaker:
       timeoutDuration: 30s
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG




