server:
  port: 8082
spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/movie_db?createDatabaseIfNotExist=true
    username: root
    password: root
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
   multipart:
    enabled=true
    max-file-size=10MB
    max-request-size=10MB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/