spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://10.0.0.52:5173
              - http://localhost:5173
            allowedMethods:
              - OPTIONS
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true

      routes:
        # User_Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**,/api/users/**
          filters:
            - name: AuthenticationFilter
              args:
                skip: false
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user-service
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                methods: GET, POST

        # Movie_Service
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api/movies/**
          filters:
            - name: AuthenticationFilter
              args:
                skip: false
            - name: CircuitBreaker
              args:
                name: movieServiceCircuitBreaker
                fallbackUri: forward:/fallback/movie-service
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                methods: GET, POST

        # Booking_Service
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**,/api/seats/**
          filters:
            - name: AuthenticationFilter
              args:
                skip: false
            - name: CircuitBreaker
              args:
                name: bookingServiceCircuitBreaker
                fallbackUri: forward:/fallback/booking-service
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                methods: GET, POST

        # Payment_Service
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
          filters:
            - name: AuthenticationFilter
              args:
                skip: false
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback/payment-service
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                methods: GET, POST

  security:
    csrf:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085

gateway:
  auth:
    open-endpoints:
      - /api/auth/login
      - /api/auth/register
      - /api/movies/getAllMovies
      - /api/movies/id/*

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 60
        slowCallDurationThreshold: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 15s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        ignoreExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException

      movieServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 60
        slowCallDurationThreshold: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 15s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        ignoreExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException

      bookingServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 60
        slowCallDurationThreshold: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 15s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        ignoreExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException

      paymentServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 60
        slowCallDurationThreshold: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 15s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        ignoreExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException

  timelimiter:
    instances:
      userServiceCircuitBreaker:
        timeoutDuration: 50s
      movieServiceCircuitBreaker:
        timeoutDuration: 30s
      bookingServiceCircuitBreaker:
        timeoutDuration: 60s
      paymentServiceCircuitBreaker:
        timeoutDuration: 30s
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers