spring:
  main:
   web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://10.0.0.52:5173
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - name: AuthenticationFilter
              args:
                skip: false
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api/movies/**
          filters:
            - name: AuthenticationFilter
              args:
                skip: false
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**,/api/seats/**
          filters:
            - name: AuthenticationFilter
              args:
                skip: false
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
          filters:
            - name: AuthenticationFilter
              args:
                skip: false
  security:
    csrf:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8085
gateway:
  auth:
    open-endpoints:
      - /api/auth/login
      - /api/auth/register
      - /api/movies/getAllMovies
      - /api/movies/id/*
      -
logging:
  level:
    org.springframework.security: DEBUG

